// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJWhOx4pposRVWyig3uh698NkFoBgSis',
    appId: '1:684142311560:web:7a247e5ccf753450ff073d',
    messagingSenderId: '684142311560',
    projectId: 'chatfirebase-d90e0',
    authDomain: 'chatfirebase-d90e0.firebaseapp.com',
    storageBucket: 'chatfirebase-d90e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtqqJ62nru2B6CnbsTgCWbiReulf6AXAQ',
    appId: '1:684142311560:android:67473be20a184a83ff073d',
    messagingSenderId: '684142311560',
    projectId: 'chatfirebase-d90e0',
    storageBucket: 'chatfirebase-d90e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHwdkSJ5SuC6TvXGqKCoOtSRRiLmb-Vk8',
    appId: '1:684142311560:ios:cdf5bcf37e65977eff073d',
    messagingSenderId: '684142311560',
    projectId: 'chatfirebase-d90e0',
    storageBucket: 'chatfirebase-d90e0.appspot.com',
    iosBundleId: 'com.example.chatfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHwdkSJ5SuC6TvXGqKCoOtSRRiLmb-Vk8',
    appId: '1:684142311560:ios:cdf5bcf37e65977eff073d',
    messagingSenderId: '684142311560',
    projectId: 'chatfirebase-d90e0',
    storageBucket: 'chatfirebase-d90e0.appspot.com',
    iosBundleId: 'com.example.chatfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnJWhOx4pposRVWyig3uh698NkFoBgSis',
    appId: '1:684142311560:web:730ea678119e71fcff073d',
    messagingSenderId: '684142311560',
    projectId: 'chatfirebase-d90e0',
    authDomain: 'chatfirebase-d90e0.firebaseapp.com',
    storageBucket: 'chatfirebase-d90e0.appspot.com',
  );
}
